# Generated by Django 3.0.3 on 2021-10-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
